[[headers]]
  for = "/*.woff2"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "font/woff2"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"